config/routes.rb
Rails.application.routes.draw do
root 'welcome#index'

resources :users
resources :ideas

get '/login', to:'sessions#new'
post '/login', to:'sessions#create'
delete '/logout', to:'sessions#destroy'

namespace :admin do
    resources :categories
  end
end

app/models/admin.rb
class Admin < ApplicationRecord


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence:true, uniqueness: true
  has_many :ideas
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  belongs_to :category
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: true
  has_many :ideas

  enum role: %w(default admin)

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    if @category.save
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to admin_category_path(@category)
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.delete
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:title, :description)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :current_admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.create(idea_params)
    @idea.user_id = current_user.id
    if @idea.save
      redirect_to @idea
    else
      render :new
    end
  end

  def show
    @idea = Idea.find(params[:id])
  end

def index
  @ideas = Idea.all
end


private

def idea_params
  params.require(:idea).permit(:name, :description,:user_id, :category_id)
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    # byebug
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to @user
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end


  def show
    @user = User.find params[:id]
    unless session[:user_id] == @user.id
      flash[:notice] = "You don't have access to that nigga!"
      redirect_to user_path(session[:user_id])
      return
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/edit.html.erb
<h1> Edit Category </h1>

<%= form_for @category, url: admin_category_path do |f| %>
<%= f.text_field :title,  placeholder: "Title" %>
<%= f.text_field :description,  placeholder: "Description (Optional)" %>
<%= f.submit "Submit Category"%>
<% end %>

app/views/admin/categories/index.html.erb
<h1> Admin Categories Menu </h1>
<%= link_to "Add New Category", new_admin_category_path %>

<% @categories.each do |category| %>
<h2><%= link_to category.title, admin_category_path(category) %></h2>
<h4><%= category.description %></h4><br>
<%= link_to "Edit", edit_admin_category_path(category) %>
<%= link_to "Delete", admin_category_path(category), method: :delete %>
<% end %>

app/views/admin/categories/new.html.erb
<h1> Add New Category </h1>

<%= form_for @category, url: admin_categories_path do |f| %>
<%= f.text_field :title,  placeholder: "Title" %>
<%= f.text_field :description,  placeholder: "Description (Optional)" %>
<%= f.submit "Submit Category"%>
<% end %>

app/views/admin/categories/show.html.erb
<h1> <%= @category.title %> </h1>

<h3><%= @category.description %></h3>

<%= link_to "Edit", edit_admin_category_path(@category) %>
<%= link_to "Delete", admin_category_path(@category), method: :delete %><br>

<br><%= link_to "Back to Category Menu", admin_categories_path %>
<br><%= link_to "Back to Dashboard", user_path(current_user.id) %>

app/views/ideas/index.html.erb
<% @user_ideas = @ideas.select do |idea| %>
<% idea.user_id == current_user.id %>
<% end %>

<% @user_ideas.each do |idea| %>
<h1> <%= idea.name %> </h1>
<h3><%= idea.description %></h3><br>
<% end %>

<%= link_to "Back to Dashboard", user_path(current_user.id) %>

app/views/ideas/new.html.erb
<h1> New Idea</h1>

<%= form_for @idea do |f|%>
<%= f.text_field :name, placeholder: "Name" %>
<%= f.text_field :description, placeholder: "Description" %>
<%= f.label :category_id, "Category" %>
<%= f.collection_select :category_id, Category.order(:title),:id, :title, prompt: true %>
<%= f.submit %>
<% end %>

app/views/ideas/show.html.erb
<h1> <%= @idea.name %> </h1>

<h3><%= @idea.description %></h3>

<%= link_to "Back to Dashboard", user_path(current_user.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<% @users.each do |user| %>
<%= user.username %>
<% end %>

app/views/users/new.html.erb
<h1> Create a New Account </h1>

<%= form_for @user do |f| %>
<%= f.text_field :username, placeholder: "Username" %>
<%= f.password_field :password, placeholder: "Password" %>

<%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h1> Welcome, <%= @user.username %>!</h1>

<%= link_to "Add New Idea", new_idea_path %><br>
<%= link_to "See all of your ideas", ideas_path %><br>
<%if current_admin? %>
<%= link_to "Categories Menu", admin_categories_path %><br>
<% end %>
<%= link_to "Logout", logout_path, method: :delete %>

app/views/welcome/index.html.erb
<h1> Welcome to Idea Box!</h1>

<%= link_to "Login", login_path %>
<%= link_to "Create New Account", new_user_path %>